/*
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGoalDSLScopeProvider extends DelegatingScopeProvider {
}
