/*
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal.ide

import ca.uwo.goal.GoalDSLRuntimeModule
import ca.uwo.goal.GoalDSLStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class GoalDSLIdeSetup extends GoalDSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new GoalDSLRuntimeModule, new GoalDSLIdeModule))
	}
	
}
