/*
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GoalDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("ca/uwo/goal/parser/antlr/internal/InternalGoalDSL.tokens");
	}
}
