/*
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal.parser.antlr;

import ca.uwo.goal.parser.antlr.internal.InternalGoalDSLParser;
import ca.uwo.goal.services.GoalDSLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GoalDSLParser extends AbstractAntlrParser {

	@Inject
	private GoalDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGoalDSLParser createParser(XtextTokenStream stream) {
		return new InternalGoalDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "GoalSpecification";
	}

	public GoalDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GoalDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
