/**
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal.goalDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Actor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uwo.goal.goalDSL.Actor#getName <em>Name</em>}</li>
 *   <li>{@link ca.uwo.goal.goalDSL.Actor#getIntentionalElements <em>Intentional Elements</em>}</li>
 *   <li>{@link ca.uwo.goal.goalDSL.Actor#getContribution <em>Contribution</em>}</li>
 * </ul>
 *
 * @see ca.uwo.goal.goalDSL.GoalDSLPackage#getActor()
 * @model
 * @generated
 */
public interface Actor extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ca.uwo.goal.goalDSL.GoalDSLPackage#getActor_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ca.uwo.goal.goalDSL.Actor#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Intentional Elements</b></em>' containment reference list.
   * The list contents are of type {@link ca.uwo.goal.goalDSL.IntentionalElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Intentional Elements</em>' containment reference list.
   * @see ca.uwo.goal.goalDSL.GoalDSLPackage#getActor_IntentionalElements()
   * @model containment="true"
   * @generated
   */
  EList<IntentionalElement> getIntentionalElements();

  /**
   * Returns the value of the '<em><b>Contribution</b></em>' containment reference list.
   * The list contents are of type {@link ca.uwo.goal.goalDSL.Contribution}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contribution</em>' containment reference list.
   * @see ca.uwo.goal.goalDSL.GoalDSLPackage#getActor_Contribution()
   * @model containment="true"
   * @generated
   */
  EList<Contribution> getContribution();

} // Actor
