/**
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal.goalDSL;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Contribution Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see ca.uwo.goal.goalDSL.GoalDSLPackage#getContributionType()
 * @model
 * @generated
 */
public enum ContributionType implements Enumerator
{
  /**
   * The '<em><b>MAKE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MAKE_VALUE
   * @generated
   * @ordered
   */
  MAKE(0, "MAKE", "++S"),

  /**
   * The '<em><b>BREAK</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BREAK_VALUE
   * @generated
   * @ordered
   */
  BREAK(1, "BREAK", "--S"),

  /**
   * The '<em><b>NEGATION MAKE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NEGATION_MAKE_VALUE
   * @generated
   * @ordered
   */
  NEGATION_MAKE(2, "NEGATION_MAKE", "++D"),

  /**
   * The '<em><b>NEGATION BREAK</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NEGATION_BREAK_VALUE
   * @generated
   * @ordered
   */
  NEGATION_BREAK(3, "NEGATION_BREAK", "--D");

  /**
   * The '<em><b>MAKE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MAKE
   * @model literal="++S"
   * @generated
   * @ordered
   */
  public static final int MAKE_VALUE = 0;

  /**
   * The '<em><b>BREAK</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BREAK
   * @model literal="--S"
   * @generated
   * @ordered
   */
  public static final int BREAK_VALUE = 1;

  /**
   * The '<em><b>NEGATION MAKE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NEGATION_MAKE
   * @model literal="++D"
   * @generated
   * @ordered
   */
  public static final int NEGATION_MAKE_VALUE = 2;

  /**
   * The '<em><b>NEGATION BREAK</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NEGATION_BREAK
   * @model literal="--D"
   * @generated
   * @ordered
   */
  public static final int NEGATION_BREAK_VALUE = 3;

  /**
   * An array of all the '<em><b>Contribution Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ContributionType[] VALUES_ARRAY =
    new ContributionType[]
    {
      MAKE,
      BREAK,
      NEGATION_MAKE,
      NEGATION_BREAK,
    };

  /**
   * A public read-only list of all the '<em><b>Contribution Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ContributionType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Contribution Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ContributionType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ContributionType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Contribution Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ContributionType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ContributionType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Contribution Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ContributionType get(int value)
  {
    switch (value)
    {
      case MAKE_VALUE: return MAKE;
      case BREAK_VALUE: return BREAK;
      case NEGATION_MAKE_VALUE: return NEGATION_MAKE;
      case NEGATION_BREAK_VALUE: return NEGATION_BREAK;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ContributionType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ContributionType
