/**
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal.goalDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contribution</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uwo.goal.goalDSL.Contribution#getSrc <em>Src</em>}</li>
 *   <li>{@link ca.uwo.goal.goalDSL.Contribution#getContributionType <em>Contribution Type</em>}</li>
 *   <li>{@link ca.uwo.goal.goalDSL.Contribution#getDest <em>Dest</em>}</li>
 * </ul>
 *
 * @see ca.uwo.goal.goalDSL.GoalDSLPackage#getContribution()
 * @model
 * @generated
 */
public interface Contribution extends EObject
{
  /**
   * Returns the value of the '<em><b>Src</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Src</em>' reference.
   * @see #setSrc(IntentionalElement)
   * @see ca.uwo.goal.goalDSL.GoalDSLPackage#getContribution_Src()
   * @model
   * @generated
   */
  IntentionalElement getSrc();

  /**
   * Sets the value of the '{@link ca.uwo.goal.goalDSL.Contribution#getSrc <em>Src</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Src</em>' reference.
   * @see #getSrc()
   * @generated
   */
  void setSrc(IntentionalElement value);

  /**
   * Returns the value of the '<em><b>Contribution Type</b></em>' attribute.
   * The literals are from the enumeration {@link ca.uwo.goal.goalDSL.ContributionType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contribution Type</em>' attribute.
   * @see ca.uwo.goal.goalDSL.ContributionType
   * @see #setContributionType(ContributionType)
   * @see ca.uwo.goal.goalDSL.GoalDSLPackage#getContribution_ContributionType()
   * @model
   * @generated
   */
  ContributionType getContributionType();

  /**
   * Sets the value of the '{@link ca.uwo.goal.goalDSL.Contribution#getContributionType <em>Contribution Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contribution Type</em>' attribute.
   * @see ca.uwo.goal.goalDSL.ContributionType
   * @see #getContributionType()
   * @generated
   */
  void setContributionType(ContributionType value);

  /**
   * Returns the value of the '<em><b>Dest</b></em>' reference list.
   * The list contents are of type {@link ca.uwo.goal.goalDSL.GoalTaskElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dest</em>' reference list.
   * @see ca.uwo.goal.goalDSL.GoalDSLPackage#getContribution_Dest()
   * @model
   * @generated
   */
  EList<GoalTaskElement> getDest();

} // Contribution
