/**
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal.goalDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Goal Task Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uwo.goal.goalDSL.GoalTaskElement#getDecompositionType <em>Decomposition Type</em>}</li>
 *   <li>{@link ca.uwo.goal.goalDSL.GoalTaskElement#getChilldren <em>Chilldren</em>}</li>
 *   <li>{@link ca.uwo.goal.goalDSL.GoalTaskElement#getParent <em>Parent</em>}</li>
 * </ul>
 *
 * @see ca.uwo.goal.goalDSL.GoalDSLPackage#getGoalTaskElement()
 * @model
 * @generated
 */
public interface GoalTaskElement extends IntentionalElement
{
  /**
   * Returns the value of the '<em><b>Decomposition Type</b></em>' attribute.
   * The literals are from the enumeration {@link ca.uwo.goal.goalDSL.DecompositionType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decomposition Type</em>' attribute.
   * @see ca.uwo.goal.goalDSL.DecompositionType
   * @see #setDecompositionType(DecompositionType)
   * @see ca.uwo.goal.goalDSL.GoalDSLPackage#getGoalTaskElement_DecompositionType()
   * @model
   * @generated
   */
  DecompositionType getDecompositionType();

  /**
   * Sets the value of the '{@link ca.uwo.goal.goalDSL.GoalTaskElement#getDecompositionType <em>Decomposition Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decomposition Type</em>' attribute.
   * @see ca.uwo.goal.goalDSL.DecompositionType
   * @see #getDecompositionType()
   * @generated
   */
  void setDecompositionType(DecompositionType value);

  /**
   * Returns the value of the '<em><b>Chilldren</b></em>' containment reference list.
   * The list contents are of type {@link ca.uwo.goal.goalDSL.GoalTaskElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chilldren</em>' containment reference list.
   * @see ca.uwo.goal.goalDSL.GoalDSLPackage#getGoalTaskElement_Chilldren()
   * @model containment="true"
   * @generated
   */
  EList<GoalTaskElement> getChilldren();

  /**
   * Returns the value of the '<em><b>Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parent</em>' reference.
   * @see #setParent(GoalTaskElement)
   * @see ca.uwo.goal.goalDSL.GoalDSLPackage#getGoalTaskElement_Parent()
   * @model
   * @generated
   */
  GoalTaskElement getParent();

  /**
   * Sets the value of the '{@link ca.uwo.goal.goalDSL.GoalTaskElement#getParent <em>Parent</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parent</em>' reference.
   * @see #getParent()
   * @generated
   */
  void setParent(GoalTaskElement value);

} // GoalTaskElement
