/**
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal.goalDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ca.uwo.goal.goalDSL.GoalDSLFactory
 * @model kind="package"
 * @generated
 */
public interface GoalDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "goalDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.uwo.ca/goal/GoalDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "goalDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GoalDSLPackage eINSTANCE = ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link ca.uwo.goal.goalDSL.impl.GoalSpecificationImpl <em>Goal Specification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.uwo.goal.goalDSL.impl.GoalSpecificationImpl
   * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getGoalSpecification()
   * @generated
   */
  int GOAL_SPECIFICATION = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL_SPECIFICATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Root</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL_SPECIFICATION__ROOT = 1;

  /**
   * The number of structural features of the '<em>Goal Specification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL_SPECIFICATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ca.uwo.goal.goalDSL.impl.RootImpl <em>Root</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.uwo.goal.goalDSL.impl.RootImpl
   * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getRoot()
   * @generated
   */
  int ROOT = 1;

  /**
   * The feature id for the '<em><b>Actors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT__ACTORS = 0;

  /**
   * The feature id for the '<em><b>Dependencies</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT__DEPENDENCIES = 1;

  /**
   * The number of structural features of the '<em>Root</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ca.uwo.goal.goalDSL.impl.IntentionalElementImpl <em>Intentional Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.uwo.goal.goalDSL.impl.IntentionalElementImpl
   * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getIntentionalElement()
   * @generated
   */
  int INTENTIONAL_ELEMENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTENTIONAL_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Intentional Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTENTIONAL_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ca.uwo.goal.goalDSL.impl.GoalTaskElementImpl <em>Goal Task Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.uwo.goal.goalDSL.impl.GoalTaskElementImpl
   * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getGoalTaskElement()
   * @generated
   */
  int GOAL_TASK_ELEMENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL_TASK_ELEMENT__NAME = INTENTIONAL_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Decomposition Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL_TASK_ELEMENT__DECOMPOSITION_TYPE = INTENTIONAL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Chilldren</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL_TASK_ELEMENT__CHILLDREN = INTENTIONAL_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL_TASK_ELEMENT__PARENT = INTENTIONAL_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Goal Task Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL_TASK_ELEMENT_FEATURE_COUNT = INTENTIONAL_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link ca.uwo.goal.goalDSL.impl.ActorImpl <em>Actor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.uwo.goal.goalDSL.impl.ActorImpl
   * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getActor()
   * @generated
   */
  int ACTOR = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Intentional Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__INTENTIONAL_ELEMENTS = 1;

  /**
   * The feature id for the '<em><b>Contribution</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__CONTRIBUTION = 2;

  /**
   * The number of structural features of the '<em>Actor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ca.uwo.goal.goalDSL.impl.GoalImpl <em>Goal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.uwo.goal.goalDSL.impl.GoalImpl
   * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getGoal()
   * @generated
   */
  int GOAL = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL__NAME = GOAL_TASK_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Decomposition Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL__DECOMPOSITION_TYPE = GOAL_TASK_ELEMENT__DECOMPOSITION_TYPE;

  /**
   * The feature id for the '<em><b>Chilldren</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL__CHILLDREN = GOAL_TASK_ELEMENT__CHILLDREN;

  /**
   * The feature id for the '<em><b>Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL__PARENT = GOAL_TASK_ELEMENT__PARENT;

  /**
   * The number of structural features of the '<em>Goal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL_FEATURE_COUNT = GOAL_TASK_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ca.uwo.goal.goalDSL.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.uwo.goal.goalDSL.impl.TaskImpl
   * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getTask()
   * @generated
   */
  int TASK = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__NAME = GOAL_TASK_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Decomposition Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__DECOMPOSITION_TYPE = GOAL_TASK_ELEMENT__DECOMPOSITION_TYPE;

  /**
   * The feature id for the '<em><b>Chilldren</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__CHILLDREN = GOAL_TASK_ELEMENT__CHILLDREN;

  /**
   * The feature id for the '<em><b>Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__PARENT = GOAL_TASK_ELEMENT__PARENT;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = GOAL_TASK_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ca.uwo.goal.goalDSL.impl.ResourceImpl <em>Resource</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.uwo.goal.goalDSL.impl.ResourceImpl
   * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getResource()
   * @generated
   */
  int RESOURCE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCE__NAME = INTENTIONAL_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Dest</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCE__DEST = INTENTIONAL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Resource</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCE_FEATURE_COUNT = INTENTIONAL_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ca.uwo.goal.goalDSL.impl.ContributionImpl <em>Contribution</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.uwo.goal.goalDSL.impl.ContributionImpl
   * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getContribution()
   * @generated
   */
  int CONTRIBUTION = 8;

  /**
   * The feature id for the '<em><b>Src</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRIBUTION__SRC = 0;

  /**
   * The feature id for the '<em><b>Contribution Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRIBUTION__CONTRIBUTION_TYPE = 1;

  /**
   * The feature id for the '<em><b>Dest</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRIBUTION__DEST = 2;

  /**
   * The number of structural features of the '<em>Contribution</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRIBUTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ca.uwo.goal.goalDSL.impl.DependencyImpl <em>Dependency</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.uwo.goal.goalDSL.impl.DependencyImpl
   * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getDependency()
   * @generated
   */
  int DEPENDENCY = 9;

  /**
   * The feature id for the '<em><b>Src</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY__SRC = 0;

  /**
   * The feature id for the '<em><b>Dest</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY__DEST = 1;

  /**
   * The number of structural features of the '<em>Dependency</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ca.uwo.goal.goalDSL.DecompositionType <em>Decomposition Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.uwo.goal.goalDSL.DecompositionType
   * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getDecompositionType()
   * @generated
   */
  int DECOMPOSITION_TYPE = 10;

  /**
   * The meta object id for the '{@link ca.uwo.goal.goalDSL.ContributionType <em>Contribution Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.uwo.goal.goalDSL.ContributionType
   * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getContributionType()
   * @generated
   */
  int CONTRIBUTION_TYPE = 11;


  /**
   * Returns the meta object for class '{@link ca.uwo.goal.goalDSL.GoalSpecification <em>Goal Specification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Goal Specification</em>'.
   * @see ca.uwo.goal.goalDSL.GoalSpecification
   * @generated
   */
  EClass getGoalSpecification();

  /**
   * Returns the meta object for the attribute '{@link ca.uwo.goal.goalDSL.GoalSpecification#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.uwo.goal.goalDSL.GoalSpecification#getName()
   * @see #getGoalSpecification()
   * @generated
   */
  EAttribute getGoalSpecification_Name();

  /**
   * Returns the meta object for the containment reference '{@link ca.uwo.goal.goalDSL.GoalSpecification#getRoot <em>Root</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Root</em>'.
   * @see ca.uwo.goal.goalDSL.GoalSpecification#getRoot()
   * @see #getGoalSpecification()
   * @generated
   */
  EReference getGoalSpecification_Root();

  /**
   * Returns the meta object for class '{@link ca.uwo.goal.goalDSL.Root <em>Root</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Root</em>'.
   * @see ca.uwo.goal.goalDSL.Root
   * @generated
   */
  EClass getRoot();

  /**
   * Returns the meta object for the containment reference list '{@link ca.uwo.goal.goalDSL.Root#getActors <em>Actors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actors</em>'.
   * @see ca.uwo.goal.goalDSL.Root#getActors()
   * @see #getRoot()
   * @generated
   */
  EReference getRoot_Actors();

  /**
   * Returns the meta object for the containment reference list '{@link ca.uwo.goal.goalDSL.Root#getDependencies <em>Dependencies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dependencies</em>'.
   * @see ca.uwo.goal.goalDSL.Root#getDependencies()
   * @see #getRoot()
   * @generated
   */
  EReference getRoot_Dependencies();

  /**
   * Returns the meta object for class '{@link ca.uwo.goal.goalDSL.IntentionalElement <em>Intentional Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Intentional Element</em>'.
   * @see ca.uwo.goal.goalDSL.IntentionalElement
   * @generated
   */
  EClass getIntentionalElement();

  /**
   * Returns the meta object for the attribute '{@link ca.uwo.goal.goalDSL.IntentionalElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.uwo.goal.goalDSL.IntentionalElement#getName()
   * @see #getIntentionalElement()
   * @generated
   */
  EAttribute getIntentionalElement_Name();

  /**
   * Returns the meta object for class '{@link ca.uwo.goal.goalDSL.GoalTaskElement <em>Goal Task Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Goal Task Element</em>'.
   * @see ca.uwo.goal.goalDSL.GoalTaskElement
   * @generated
   */
  EClass getGoalTaskElement();

  /**
   * Returns the meta object for the attribute '{@link ca.uwo.goal.goalDSL.GoalTaskElement#getDecompositionType <em>Decomposition Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Decomposition Type</em>'.
   * @see ca.uwo.goal.goalDSL.GoalTaskElement#getDecompositionType()
   * @see #getGoalTaskElement()
   * @generated
   */
  EAttribute getGoalTaskElement_DecompositionType();

  /**
   * Returns the meta object for the containment reference list '{@link ca.uwo.goal.goalDSL.GoalTaskElement#getChilldren <em>Chilldren</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Chilldren</em>'.
   * @see ca.uwo.goal.goalDSL.GoalTaskElement#getChilldren()
   * @see #getGoalTaskElement()
   * @generated
   */
  EReference getGoalTaskElement_Chilldren();

  /**
   * Returns the meta object for the reference '{@link ca.uwo.goal.goalDSL.GoalTaskElement#getParent <em>Parent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Parent</em>'.
   * @see ca.uwo.goal.goalDSL.GoalTaskElement#getParent()
   * @see #getGoalTaskElement()
   * @generated
   */
  EReference getGoalTaskElement_Parent();

  /**
   * Returns the meta object for class '{@link ca.uwo.goal.goalDSL.Actor <em>Actor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actor</em>'.
   * @see ca.uwo.goal.goalDSL.Actor
   * @generated
   */
  EClass getActor();

  /**
   * Returns the meta object for the attribute '{@link ca.uwo.goal.goalDSL.Actor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.uwo.goal.goalDSL.Actor#getName()
   * @see #getActor()
   * @generated
   */
  EAttribute getActor_Name();

  /**
   * Returns the meta object for the containment reference list '{@link ca.uwo.goal.goalDSL.Actor#getIntentionalElements <em>Intentional Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Intentional Elements</em>'.
   * @see ca.uwo.goal.goalDSL.Actor#getIntentionalElements()
   * @see #getActor()
   * @generated
   */
  EReference getActor_IntentionalElements();

  /**
   * Returns the meta object for the containment reference list '{@link ca.uwo.goal.goalDSL.Actor#getContribution <em>Contribution</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Contribution</em>'.
   * @see ca.uwo.goal.goalDSL.Actor#getContribution()
   * @see #getActor()
   * @generated
   */
  EReference getActor_Contribution();

  /**
   * Returns the meta object for class '{@link ca.uwo.goal.goalDSL.Goal <em>Goal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Goal</em>'.
   * @see ca.uwo.goal.goalDSL.Goal
   * @generated
   */
  EClass getGoal();

  /**
   * Returns the meta object for class '{@link ca.uwo.goal.goalDSL.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see ca.uwo.goal.goalDSL.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for class '{@link ca.uwo.goal.goalDSL.Resource <em>Resource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Resource</em>'.
   * @see ca.uwo.goal.goalDSL.Resource
   * @generated
   */
  EClass getResource();

  /**
   * Returns the meta object for the reference list '{@link ca.uwo.goal.goalDSL.Resource#getDest <em>Dest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Dest</em>'.
   * @see ca.uwo.goal.goalDSL.Resource#getDest()
   * @see #getResource()
   * @generated
   */
  EReference getResource_Dest();

  /**
   * Returns the meta object for class '{@link ca.uwo.goal.goalDSL.Contribution <em>Contribution</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contribution</em>'.
   * @see ca.uwo.goal.goalDSL.Contribution
   * @generated
   */
  EClass getContribution();

  /**
   * Returns the meta object for the reference '{@link ca.uwo.goal.goalDSL.Contribution#getSrc <em>Src</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Src</em>'.
   * @see ca.uwo.goal.goalDSL.Contribution#getSrc()
   * @see #getContribution()
   * @generated
   */
  EReference getContribution_Src();

  /**
   * Returns the meta object for the attribute '{@link ca.uwo.goal.goalDSL.Contribution#getContributionType <em>Contribution Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Contribution Type</em>'.
   * @see ca.uwo.goal.goalDSL.Contribution#getContributionType()
   * @see #getContribution()
   * @generated
   */
  EAttribute getContribution_ContributionType();

  /**
   * Returns the meta object for the reference list '{@link ca.uwo.goal.goalDSL.Contribution#getDest <em>Dest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Dest</em>'.
   * @see ca.uwo.goal.goalDSL.Contribution#getDest()
   * @see #getContribution()
   * @generated
   */
  EReference getContribution_Dest();

  /**
   * Returns the meta object for class '{@link ca.uwo.goal.goalDSL.Dependency <em>Dependency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dependency</em>'.
   * @see ca.uwo.goal.goalDSL.Dependency
   * @generated
   */
  EClass getDependency();

  /**
   * Returns the meta object for the reference '{@link ca.uwo.goal.goalDSL.Dependency#getSrc <em>Src</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Src</em>'.
   * @see ca.uwo.goal.goalDSL.Dependency#getSrc()
   * @see #getDependency()
   * @generated
   */
  EReference getDependency_Src();

  /**
   * Returns the meta object for the reference list '{@link ca.uwo.goal.goalDSL.Dependency#getDest <em>Dest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Dest</em>'.
   * @see ca.uwo.goal.goalDSL.Dependency#getDest()
   * @see #getDependency()
   * @generated
   */
  EReference getDependency_Dest();

  /**
   * Returns the meta object for enum '{@link ca.uwo.goal.goalDSL.DecompositionType <em>Decomposition Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Decomposition Type</em>'.
   * @see ca.uwo.goal.goalDSL.DecompositionType
   * @generated
   */
  EEnum getDecompositionType();

  /**
   * Returns the meta object for enum '{@link ca.uwo.goal.goalDSL.ContributionType <em>Contribution Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Contribution Type</em>'.
   * @see ca.uwo.goal.goalDSL.ContributionType
   * @generated
   */
  EEnum getContributionType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GoalDSLFactory getGoalDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ca.uwo.goal.goalDSL.impl.GoalSpecificationImpl <em>Goal Specification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.uwo.goal.goalDSL.impl.GoalSpecificationImpl
     * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getGoalSpecification()
     * @generated
     */
    EClass GOAL_SPECIFICATION = eINSTANCE.getGoalSpecification();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOAL_SPECIFICATION__NAME = eINSTANCE.getGoalSpecification_Name();

    /**
     * The meta object literal for the '<em><b>Root</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GOAL_SPECIFICATION__ROOT = eINSTANCE.getGoalSpecification_Root();

    /**
     * The meta object literal for the '{@link ca.uwo.goal.goalDSL.impl.RootImpl <em>Root</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.uwo.goal.goalDSL.impl.RootImpl
     * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getRoot()
     * @generated
     */
    EClass ROOT = eINSTANCE.getRoot();

    /**
     * The meta object literal for the '<em><b>Actors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOT__ACTORS = eINSTANCE.getRoot_Actors();

    /**
     * The meta object literal for the '<em><b>Dependencies</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOT__DEPENDENCIES = eINSTANCE.getRoot_Dependencies();

    /**
     * The meta object literal for the '{@link ca.uwo.goal.goalDSL.impl.IntentionalElementImpl <em>Intentional Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.uwo.goal.goalDSL.impl.IntentionalElementImpl
     * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getIntentionalElement()
     * @generated
     */
    EClass INTENTIONAL_ELEMENT = eINSTANCE.getIntentionalElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTENTIONAL_ELEMENT__NAME = eINSTANCE.getIntentionalElement_Name();

    /**
     * The meta object literal for the '{@link ca.uwo.goal.goalDSL.impl.GoalTaskElementImpl <em>Goal Task Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.uwo.goal.goalDSL.impl.GoalTaskElementImpl
     * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getGoalTaskElement()
     * @generated
     */
    EClass GOAL_TASK_ELEMENT = eINSTANCE.getGoalTaskElement();

    /**
     * The meta object literal for the '<em><b>Decomposition Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOAL_TASK_ELEMENT__DECOMPOSITION_TYPE = eINSTANCE.getGoalTaskElement_DecompositionType();

    /**
     * The meta object literal for the '<em><b>Chilldren</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GOAL_TASK_ELEMENT__CHILLDREN = eINSTANCE.getGoalTaskElement_Chilldren();

    /**
     * The meta object literal for the '<em><b>Parent</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GOAL_TASK_ELEMENT__PARENT = eINSTANCE.getGoalTaskElement_Parent();

    /**
     * The meta object literal for the '{@link ca.uwo.goal.goalDSL.impl.ActorImpl <em>Actor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.uwo.goal.goalDSL.impl.ActorImpl
     * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getActor()
     * @generated
     */
    EClass ACTOR = eINSTANCE.getActor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTOR__NAME = eINSTANCE.getActor_Name();

    /**
     * The meta object literal for the '<em><b>Intentional Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTOR__INTENTIONAL_ELEMENTS = eINSTANCE.getActor_IntentionalElements();

    /**
     * The meta object literal for the '<em><b>Contribution</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTOR__CONTRIBUTION = eINSTANCE.getActor_Contribution();

    /**
     * The meta object literal for the '{@link ca.uwo.goal.goalDSL.impl.GoalImpl <em>Goal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.uwo.goal.goalDSL.impl.GoalImpl
     * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getGoal()
     * @generated
     */
    EClass GOAL = eINSTANCE.getGoal();

    /**
     * The meta object literal for the '{@link ca.uwo.goal.goalDSL.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.uwo.goal.goalDSL.impl.TaskImpl
     * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '{@link ca.uwo.goal.goalDSL.impl.ResourceImpl <em>Resource</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.uwo.goal.goalDSL.impl.ResourceImpl
     * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getResource()
     * @generated
     */
    EClass RESOURCE = eINSTANCE.getResource();

    /**
     * The meta object literal for the '<em><b>Dest</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESOURCE__DEST = eINSTANCE.getResource_Dest();

    /**
     * The meta object literal for the '{@link ca.uwo.goal.goalDSL.impl.ContributionImpl <em>Contribution</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.uwo.goal.goalDSL.impl.ContributionImpl
     * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getContribution()
     * @generated
     */
    EClass CONTRIBUTION = eINSTANCE.getContribution();

    /**
     * The meta object literal for the '<em><b>Src</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTRIBUTION__SRC = eINSTANCE.getContribution_Src();

    /**
     * The meta object literal for the '<em><b>Contribution Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTRIBUTION__CONTRIBUTION_TYPE = eINSTANCE.getContribution_ContributionType();

    /**
     * The meta object literal for the '<em><b>Dest</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTRIBUTION__DEST = eINSTANCE.getContribution_Dest();

    /**
     * The meta object literal for the '{@link ca.uwo.goal.goalDSL.impl.DependencyImpl <em>Dependency</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.uwo.goal.goalDSL.impl.DependencyImpl
     * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getDependency()
     * @generated
     */
    EClass DEPENDENCY = eINSTANCE.getDependency();

    /**
     * The meta object literal for the '<em><b>Src</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPENDENCY__SRC = eINSTANCE.getDependency_Src();

    /**
     * The meta object literal for the '<em><b>Dest</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPENDENCY__DEST = eINSTANCE.getDependency_Dest();

    /**
     * The meta object literal for the '{@link ca.uwo.goal.goalDSL.DecompositionType <em>Decomposition Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.uwo.goal.goalDSL.DecompositionType
     * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getDecompositionType()
     * @generated
     */
    EEnum DECOMPOSITION_TYPE = eINSTANCE.getDecompositionType();

    /**
     * The meta object literal for the '{@link ca.uwo.goal.goalDSL.ContributionType <em>Contribution Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.uwo.goal.goalDSL.ContributionType
     * @see ca.uwo.goal.goalDSL.impl.GoalDSLPackageImpl#getContributionType()
     * @generated
     */
    EEnum CONTRIBUTION_TYPE = eINSTANCE.getContributionType();

  }

} //GoalDSLPackage
