/**
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal.goalDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Root</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uwo.goal.goalDSL.Root#getActors <em>Actors</em>}</li>
 *   <li>{@link ca.uwo.goal.goalDSL.Root#getDependencies <em>Dependencies</em>}</li>
 * </ul>
 *
 * @see ca.uwo.goal.goalDSL.GoalDSLPackage#getRoot()
 * @model
 * @generated
 */
public interface Root extends EObject
{
  /**
   * Returns the value of the '<em><b>Actors</b></em>' containment reference list.
   * The list contents are of type {@link ca.uwo.goal.goalDSL.Actor}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actors</em>' containment reference list.
   * @see ca.uwo.goal.goalDSL.GoalDSLPackage#getRoot_Actors()
   * @model containment="true"
   * @generated
   */
  EList<Actor> getActors();

  /**
   * Returns the value of the '<em><b>Dependencies</b></em>' containment reference list.
   * The list contents are of type {@link ca.uwo.goal.goalDSL.Dependency}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dependencies</em>' containment reference list.
   * @see ca.uwo.goal.goalDSL.GoalDSLPackage#getRoot_Dependencies()
   * @model containment="true"
   * @generated
   */
  EList<Dependency> getDependencies();

} // Root
