/**
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal.goalDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ca.uwo.goal.goalDSL.GoalDSLPackage#getTask()
 * @model
 * @generated
 */
public interface Task extends GoalTaskElement
{
} // Task
