/*
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class GoalDSLUiModule extends AbstractGoalDSLUiModule {
}
