/*
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GoalDSLStandaloneSetup extends GoalDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new GoalDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
