/*
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GoalDSLRuntimeModule extends AbstractGoalDSLRuntimeModule {
}
