/*
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal.ui.tests;

import ca.uwo.goal.ui.internal.GoalActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GoalDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GoalActivator.getInstance().getInjector("ca.uwo.goal.GoalDSL");
	}

}
