/*
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal.ui;

import ca.uwo.goal.ui.internal.GoalActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GoalDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(GoalActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		GoalActivator activator = GoalActivator.getInstance();
		return activator != null ? activator.getInjector(GoalActivator.CA_UWO_GOAL_GOALDSL) : null;
	}

}
