/*
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractGoalDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(ca.uwo.goal.goalDSL.GoalDSLPackage.eINSTANCE);
		return result;
	}
}
