/**
 * generated by Xtext 2.32.0
 */
package ca.uwo.goal.goalDSL.impl;

import ca.uwo.goal.goalDSL.Contribution;
import ca.uwo.goal.goalDSL.ContributionType;
import ca.uwo.goal.goalDSL.GoalDSLPackage;
import ca.uwo.goal.goalDSL.GoalTaskElement;
import ca.uwo.goal.goalDSL.IntentionalElement;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Contribution</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.uwo.goal.goalDSL.impl.ContributionImpl#getSrc <em>Src</em>}</li>
 *   <li>{@link ca.uwo.goal.goalDSL.impl.ContributionImpl#getContributionType <em>Contribution Type</em>}</li>
 *   <li>{@link ca.uwo.goal.goalDSL.impl.ContributionImpl#getDest <em>Dest</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ContributionImpl extends MinimalEObjectImpl.Container implements Contribution
{
  /**
   * The cached value of the '{@link #getSrc() <em>Src</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSrc()
   * @generated
   * @ordered
   */
  protected IntentionalElement src;

  /**
   * The default value of the '{@link #getContributionType() <em>Contribution Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContributionType()
   * @generated
   * @ordered
   */
  protected static final ContributionType CONTRIBUTION_TYPE_EDEFAULT = ContributionType.MAKE;

  /**
   * The cached value of the '{@link #getContributionType() <em>Contribution Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContributionType()
   * @generated
   * @ordered
   */
  protected ContributionType contributionType = CONTRIBUTION_TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getDest() <em>Dest</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDest()
   * @generated
   * @ordered
   */
  protected EList<GoalTaskElement> dest;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ContributionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoalDSLPackage.Literals.CONTRIBUTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntentionalElement getSrc()
  {
    if (src != null && src.eIsProxy())
    {
      InternalEObject oldSrc = (InternalEObject)src;
      src = (IntentionalElement)eResolveProxy(oldSrc);
      if (src != oldSrc)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GoalDSLPackage.CONTRIBUTION__SRC, oldSrc, src));
      }
    }
    return src;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IntentionalElement basicGetSrc()
  {
    return src;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSrc(IntentionalElement newSrc)
  {
    IntentionalElement oldSrc = src;
    src = newSrc;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoalDSLPackage.CONTRIBUTION__SRC, oldSrc, src));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ContributionType getContributionType()
  {
    return contributionType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setContributionType(ContributionType newContributionType)
  {
    ContributionType oldContributionType = contributionType;
    contributionType = newContributionType == null ? CONTRIBUTION_TYPE_EDEFAULT : newContributionType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoalDSLPackage.CONTRIBUTION__CONTRIBUTION_TYPE, oldContributionType, contributionType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<GoalTaskElement> getDest()
  {
    if (dest == null)
    {
      dest = new EObjectResolvingEList<GoalTaskElement>(GoalTaskElement.class, this, GoalDSLPackage.CONTRIBUTION__DEST);
    }
    return dest;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GoalDSLPackage.CONTRIBUTION__SRC:
        if (resolve) return getSrc();
        return basicGetSrc();
      case GoalDSLPackage.CONTRIBUTION__CONTRIBUTION_TYPE:
        return getContributionType();
      case GoalDSLPackage.CONTRIBUTION__DEST:
        return getDest();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GoalDSLPackage.CONTRIBUTION__SRC:
        setSrc((IntentionalElement)newValue);
        return;
      case GoalDSLPackage.CONTRIBUTION__CONTRIBUTION_TYPE:
        setContributionType((ContributionType)newValue);
        return;
      case GoalDSLPackage.CONTRIBUTION__DEST:
        getDest().clear();
        getDest().addAll((Collection<? extends GoalTaskElement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GoalDSLPackage.CONTRIBUTION__SRC:
        setSrc((IntentionalElement)null);
        return;
      case GoalDSLPackage.CONTRIBUTION__CONTRIBUTION_TYPE:
        setContributionType(CONTRIBUTION_TYPE_EDEFAULT);
        return;
      case GoalDSLPackage.CONTRIBUTION__DEST:
        getDest().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GoalDSLPackage.CONTRIBUTION__SRC:
        return src != null;
      case GoalDSLPackage.CONTRIBUTION__CONTRIBUTION_TYPE:
        return contributionType != CONTRIBUTION_TYPE_EDEFAULT;
      case GoalDSLPackage.CONTRIBUTION__DEST:
        return dest != null && !dest.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (contributionType: ");
    result.append(contributionType);
    result.append(')');
    return result.toString();
  }

} //ContributionImpl
